# Generated by Django 3.0 on 2022-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='b_date',
            field=models.DateField(null=True),
        ),
    ]
