# Generated by Django 3.0 on 2022-12-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_user_b_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('favorite_book', models.ManyToManyField(related_name='favorites', to='myapp.User')),
                ('uploaded_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.User')),
            ],
        ),
    ]
